{% set name = "xlwings" %}
{% set version = "0.26.1" %}
{% set sha256 = "2891008fbb07991fc6ac6fea716e8f50f0c181c9b07ab4031a1c64480ae2abc7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - xlwings = xlwings.cli:main
  skip: true  # [linux or py<36]

requirements:
  host:
    - python
    - setuptools
    - wheel
  run:
    - python
    - pywin32 >=224  # [win and py>=37]
    - pywin32  # [win and py36]
    - psutil >=2.0.0  # [osx]
    - appscript >=1.0.1  # [osx]

test:
  requires:
    - pip
  commands:
    - pip check
    - xlwings -h
  imports:
    - xlwings
    - xlwings.conversion

about:
  home: http://xlwings.org/
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Interact with Excel from Python and vice versa
  description: |
    xlwings is a BSD-licensed Python library that makes it easy to call Python from Excel and vice versa.
  doc_url: http://docs.xlwings.org/en/stable/index.html
  dev_url: https://github.com/ZoomerAnalytics/xlwings
  doc_source_url: https://github.com/ZoomerAnalytics/xlwings/blob/master/docs/quickstart.rst

extra:
  recipe-maintainers:
    - fzumstein
