{% set name = "xlwings" %}
{% set version = "0.31.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: de9ccbb35aa90f7e31264a53e7ee8ad2ccce771f055cef1463faa3683880a873

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  entry_points:
    - xlwings = xlwings.cli:main
  skip: true  # [linux or py<38]

requirements:
  host:
    - python
    - pip
    - maturin 1.3.0
  run:
    - python
    - pywin32 >=224 # [win]
    - psutil >=2.0  # [osx]
    - appscript >=1.0.1  # [osx]

test:
  requires:
    - pip
    - werkzeug
    - flask
  commands:
    - pip check
    - xlwings -h
  imports:
    - xlwings
    - xlwings.conversion
    - xlwings.ext
    - xlwings.quickstart_fastapi
    - xlwings.rest

about:
  home: https://www.xlwings.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Interact with Excel from Python and vice versa
  description: |
    xlwings is a BSD-licensed Python library that makes it easy to call Python from Excel and vice versa.
  doc_url: https://docs.xlwings.org/
  dev_url: https://github.com/xlwings/xlwings

extra:
  skip-lints:
    - missing_wheel
  recipe-maintainers:
    - fzumstein
