{% set name = "xlwings" %}
{% set version = "0.15.5" %}
{% set sha256 = "a121eeb2de2e0d7cb963a1860da837e5773dd05cda09a0df4d1d8d29786344f4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - xlwings = xlwings.command_line:main
  skip: True  # [linux]

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - comtypes  # [win]
    - pywin32  # [win]
    - psutil >=2.0  # [osx]
    - appscript >=1.0.1  # [osx]

test:
  commands:
    - xlwings -h
  imports:
    - xlwings
    - xlwings.conversion

about:
  home: http://xlwings.org/
  license: 3-clause BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Interact with Excel from Python and vice versa
  description: |
     xlwings is a BSD-licensed Python library that makes it easy to call Python from Excel and vice versa.
  doc_url: http://docs.xlwings.org/en/stable/index.html
  dev_url: https://github.com/ZoomerAnalytics/xlwings
  doc_source_url: https://github.com/ZoomerAnalytics/xlwings/blob/master/docs/quickstart.rst

extra:
  recipe-maintainers:
    - nirajd
    - fzumstein
