{% set name = "xlwings" %}
{% set version = "0.16.2" %}
{% set sha256 = "f2cd4af5d575c7d3c123a6298d6b481e4d9b4e6a266f6ff8538dd5bb1185e1a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - xlwings = xlwings.command_line:main
  skip: True  # [linux]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - comtypes  # [win]
    - pywin32  # [win]
    - psutil >=2.0  # [osx]
    - appscript >=1.0.1  # [osx]

test:
  commands:
    - xlwings -h
  imports:
    - xlwings
    - xlwings.conversion

about:
  home: http://xlwings.org/
  license: 3-clause BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Interact with Excel from Python and vice versa
  description: |
     xlwings is a BSD-licensed Python library that makes it easy to call Python from Excel and vice versa.
  doc_url: http://docs.xlwings.org/en/stable/index.html
  dev_url: https://github.com/ZoomerAnalytics/xlwings

extra:
  recipe-maintainers:
    - fzumstein
