travis:
  secure:
    BINSTAR_TOKEN: RDVTNrXcw9gQ56KFO03z5PkpJH5x8E/Q26x/8l8fgu406iC1nZsOirs0FNyZveDpm+jxe5EQoTc0g1PmpnMmLi5+8f20zqnHb8MJ+He+AqjTDYrpDkg0kwl0sSWguoXb0NGt21hm1Cv/yEmwRLfuHak/ORv/6pm5+eBb4swrNb/8fNfOUHwl2djZYVAgYO3rYADhkJCoGu/BACRRILYe7PaYMP0GkuECTn7EkL7I8RvTa9wv8n1YyNFmyS5ezpuZhOQp1RU0eJ2kvbIgwUJuiTeFARAinBgZu3JaF59yi9BD/aTuaRbmyZ3+motgApI2FVcMBYk4yBQRfrkpSIjwxo2zIqp8nfS5AV5c+pYFuIPANBsyYq7F6IhuS6oV6kRVAMvFwHNBLuxGqx0rmHJO6ridQ5CuC9r6uNZYqYjnQQERXN8q2GD3a3YH98DOgv0AdLxzaUZWl10iNUjGOXnov3l0/TjZKrwBRLsfhwMcgWPbuklYJ1/9l21EzF1VVA2sxflGqOn0pfCUaRgCXf3VAMMtOVVBTYzhuSq1j4+pSUm+mrmWJTvkYMHoeLpAUW1k46Cd7CHf0zgxWYBoMeOf+W4PlKPx55zOfkxOhKYkdUYUozqKHnWX3whUHa/6OZFadYOlMlObzqGEK2wg02VCO1ARobbopEMfqHNU1SS7YhI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
